language: csharp
solution: Dotnet.Func.Ext.sln
dotnet: 2.0.0
dist: trusty
mono: none
script:
  - dotnet restore
  - dotnet build
  - dotnet test -c Release Dotnet.Func.Ext.Tests/Dotnet.Func.Ext.Tests.csproj
